openapi: 3.2.0
info:
  title: Integration Email API
  description: This API collection represents the integration APIs LendKey offers for 3rd party dependencies/integrations, and is for dev/qa use only. External connections are not prohibited following this document.
  termsOfService: http://www.lendkey.com
  license:
    name: Lendkey License
    url: http://www.lendkey.com
  version: 1.0.0
  contact:
    name: LendKey Product Operations Team
    url: http://www.lendkey.com
    email: HIL_product_team@lendkey.com
servers:
- url: https://proxy.kong.lkeyprod.com/integration/
  description: This is the production host for our API endpoints.
- url: https://proxy.kong.lkeystaging.com/integration/
  description: This is the staging host for our API endpoints. Please note that the ability to create a soft-pull is disabled in this environment. If credit pull testing in this environment is needed, please reach out to coordinate that.
- url: https://proxy.kong.eks-1.use-1.lkeyqa.com/integration/integration-api-spring-boot-main/
  description: This is the QA host for our API endpoints. Please use this for all development and testing purposes.
- url: '{protocol}://{env}-integration-api-spring-boot.ci.lkeyqa.com:{port}/{basePath}'
  description: The testing API server
  variables:
    protocol:
      enum:
      - http
      - https
      default: https
    env:
      default: staging
      description: 'This value is related to the environment you are running. ie: PR-1112, develop'
    port:
      enum:
      - '8443'
      - '443'
      default: '8443'
    basePath:
      description: 'Version path. ie: v1'
      default: ''
- url: http://localhost:{port}/{basePath}
  description: The local development server
  variables:
    protocol:
      enum:
      - http
      - https
      default: https
    env:
      default: develop
      description: 'this value is related to the environment you are running. ie: PR-1112, develop'
    port:
      default: '8080'
    basePath:
      description: 'Version path. ie: v1'
      default: ''
tags:
- name: email
paths:
  /v1/notifications/emails:
    summary: Endpoints for all things email related.
    post:
      tags:
      - email
      summary: Send An Email Notification
      description: Sends an email notification.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailRecordRequestPayload'
      responses:
        202:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/emailRecord'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/UnexpectedError'
  /v1/notifications/emails/templates:
    get:
      tags:
      - email
      summary: Returns a list of ALL email templates available for use via notifier-api.
      description: Lists out ALL email templates known to this service, regardless of their provider (i.e. SendGrid).
      responses:
        200:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/emailTemplateList'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/UnexpectedError'
components:
  responses:
    BadRequest:
      description: Invalid request, unable to process the request with the information provided.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: b6c52a48-551a-42ef-b361-f642d25cfeb7
            status: BAD_REQUEST
            timestamp: '2019-10-21 14:07:59'
            message: Describes what was invalid about the request, if possible.
            debugMessage: null
    UnexpectedError:
      description: An unexpected server error occurred.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: b6c52a48-551a-42ef-b361-f642d25cfeb7
            status: INTERNAL_SERVER_ERROR
            timestamp: '2019-10-21 14:07:59'
            message: An internal issue occurred.  Please try again shortly.  If the issue persists, contact us with all of the data in this error message.
            debugMessage: null
  schemas:
    suberror:
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
        message:
          type: string
      example:
        object: Resource
        field: name
        rejectedValue: null
        message: must not be null
    emailRecordDto:
      type: object
      required:
      - fromName
      - contentType
      properties:
        emailTemplate:
          type: string
          description: Optional. Specifies which email template should be used - uses a default template with no handlebar tags if one is not provided.
          example: HIL_Application_Invitation
        fromAddress:
          type: string
          description: Required. Specifies who the recipient will see the email is from.
          example: john.doe@test.com
        fromName:
          type: string
          description: Required. Specifies the name the recipient will see the email is from.
          example: John Doe
        to:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/recipient'
          description: Optional, if at least one bcc recipient is provided - otherwise at least one required. The Recipient(s) of the email.
        bcc:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/recipient'
          description: Optional, if at least one to recipient is provided - otherwise at least one required. The BCC Recipient(s) of the email.
        subject:
          type: string
          description: Optional - however certain templates may not support overriding the subject contents.
          example: Your Attention Required!
        body:
          type: string
          description: Optional - however certain templates may not support overriding the body contents.
          example: We need more information from you before we can proceed with your application. Please call us!
        contentType:
          type: string
          description: Required if body is provided. The content type of the email.
          example: text/plain
        personalizations:
          type: object
          description: Optional. Required only if a template is specified that contains handlebar tags.
          additionalProperties:
            type: object
            properties:
              personalizationTagKeyName:
                type: string
                description: The handlebar tag name, as specified in the email template, which is to be overridden with the corresponding value.
              personalizaitonTagValue:
                type: string
                description: The value to be inserted for the given handlebar tag in the specified email template.
          example:
            dealName: Example
            clientName: Some Credit Union
            subject: Boarding File Success
            firstName: John
            lastName: Doe
            body: We've received your document.
    recipient:
      type: object
      required:
      - recipientAddress
      - recipientName
      properties:
        recipientAddress:
          type: string
        recipientName:
          type: string
      example:
        recipientName: John Doe
        recipientAddress: doe.john@gmali.com
    emailTemplateList:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            emailTemplates:
              type: array
              items:
                $ref: '#/components/schemas/emailTemplate'
        _links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/link'
        page:
          $ref: '#/components/schemas/page'
      example:
        _embedded:
          emailTemplates:
          - keyName: HIL_Application_Invitation
            externalTemplateProvider: SendGrid
            externalTemplateId: ''
            emailSubstitutions:
            - id: 2
              tag: clientName
            - id: 1
              tag: dealName
        _links:
          self:
            href: http://localhost:8080/v1/emailTemplates?page=0&size=20
          first:
            href: http://localhost:8080/v1/emailTemplates?page=0&size=20
          next:
            href: http://localhost:8080/v1/emailTemplates?page=1&size=20
          last:
            href: http://localhost:8080/v1/emailTemplates?page=1&size=20
        page:
          size: 20
          totalElements: 1
          totalPages: 1
          number: 0
    link:
      type: object
      properties:
        href:
          type: string
    error:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
        timestamp:
          type: string
        message:
          type: string
        debugMessage:
          type: string
        subErrors:
          type: array
          items:
            $ref: '#/components/schemas/suberror'
      example:
        id: null
        status: BAD_REQUEST
        timestamp: '2019-10-21 14:07:59'
        message: Validation error
        debugMessage: null
        subErrors:
        - object: Resource
          field: name
          rejectedValue: null
          message: must not be null
    emailRecordRequestPayload:
      type: object
      required:
      - provider
      - paylaod
      properties:
        provider:
          type: string
          description: The email service provider to use when sending this email.
          example: SENDGRID
        payload:
          type: object
          anyOf:
          - $ref: '#/components/schemas/emailRecordDto'
    emailRecord:
      type: object
      properties:
        emailTemplate:
          type: string
          description: Optional. Specifies which email template should be used - uses a default template with no handlebar tags if one is not provided.
          example: DEFAULT
        fromAddress:
          type: string
          description: Required. Specifies who the recipient will see the 'from' email address is.
        fromName:
          type: string
          description: Required. Specifies who the recipient will see the email is from.
        to:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/recipient'
          description: Optional, if at least one bcc recipient is provided - otherwise at least one required. The Recipient(s) of the email.
        bcc:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/recipient'
          description: Optional, if at least one to recipient is provided - otherwise at least one required. The BCC Recipient(s) of the email.
        subject:
          type: string
          description: Required - however certain templates may not support overriding the subject contents.
        body:
          type: string
          description: Optional. The content body of the email, if present.
        contentType:
          type: string
          description: Required if body is provided. The content type of the email.
        sentAt:
          type: string
          format: date-time
          description: When the email was sent.
        responseReceivedAt:
          type: string
          format: date-time
          description: Tracks when this emails response was received.
        responseStatusCode:
          type: integer
          description: Tracks the response code to this email.
        responseBody:
          type: string
          description: Tracks the response body of this email.
        clientApplication:
          type: string
          description: Specifies which client application requested this email be sent.
        clientApplicationUser:
          type: string
          description: Specifies the user of the client application that requested the email be sent, or the system user.
        personalizations:
          type: object
          description: Optional. Required only if a template is specified that contains handlebar tags.
          additionalProperties:
            type: object
            properties:
              personalizationTagKeyName:
                type: string
                description: The handlebar tag name, as specified in the email template, which is to be overridden with the corresponding value.
              personalizaitonTagValue:
                type: string
                description: The value to be inserted for the given handlebar tag in the specified email template.
          example:
            dealName: Example
            clientName: Some Credit Union
            subject: Boarding File Success
            firstName: John
            lastName: Doe
            body: We've received your document.
      example:
        emailTemplate: xx-sasdgkji2h3sdsfs
        fromName: LendKey
        fromAddress: something@lendkey.com
        to:
        - recipientName: John Doe
          recipientAddress: doe.john@gmali.com
        bcc:
        - recipientName: Jane Doe
          recipientAddress: doe.jane@gmali.com
        subject: Test
        body: Test
        contentType: text/plain
        sentAt: 2021-08-1310:39:59
        responseReceivedAt: 2021-08-1310:40:03
        responseStatusCode: '202'
        responseBody: Example body
        clientApplication: DSP
        clientApplicationUser: john.doe@lendkey.com
        personalizations:
          dealName: Example
          clientName: Some Credit Union
          subject: Boarding File Success
          firstName: John
          lastName: Doe
          body: We've received your document.
    emailTemplate:
      type: object
      properties:
        keyName:
          type: string
        externalTemplateProvider:
          type: string
        externalTemplateId:
          type: string
        emailSubstitutions:
          type: array
          items:
            $ref: '#/components/schemas/emailSubstitution'
      example:
        keyName: HIL_Application_Invitation
        externalTemplateProvider: SendGrid
        externalTemplateId: ''
        emailSubstitutions:
        - $ref: '#/components/schemas/emailSubstitution'
    page:
      type: object
      properties:
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer
        number:
          type: integer
    emailSubstitution:
      type: object
      properties:
        id:
          type: integer
        tag:
          type: string
      example:
        id: 2
        tag: clientName
