openapi: 3.2.0
info:
  title: Integration Applications API
  description: This API collection represents the integration APIs LendKey offers for 3rd party dependencies/integrations, and is for dev/qa use only. External connections are not prohibited following this document.
  termsOfService: http://www.lendkey.com
  license:
    name: Lendkey License
    url: http://www.lendkey.com
  version: 1.0.0
  contact:
    name: LendKey Product Operations Team
    url: http://www.lendkey.com
    email: HIL_product_team@lendkey.com
servers:
- url: https://proxy.kong.lkeyprod.com/integration/
  description: This is the production host for our API endpoints.
- url: https://proxy.kong.lkeystaging.com/integration/
  description: This is the staging host for our API endpoints. Please note that the ability to create a soft-pull is disabled in this environment. If credit pull testing in this environment is needed, please reach out to coordinate that.
- url: https://proxy.kong.eks-1.use-1.lkeyqa.com/integration/integration-api-spring-boot-main/
  description: This is the QA host for our API endpoints. Please use this for all development and testing purposes.
- url: '{protocol}://{env}-integration-api-spring-boot.ci.lkeyqa.com:{port}/{basePath}'
  description: The testing API server
  variables:
    protocol:
      enum:
      - http
      - https
      default: https
    env:
      default: staging
      description: 'This value is related to the environment you are running. ie: PR-1112, develop'
    port:
      enum:
      - '8443'
      - '443'
      default: '8443'
    basePath:
      description: 'Version path. ie: v1'
      default: ''
- url: http://localhost:{port}/{basePath}
  description: The local development server
  variables:
    protocol:
      enum:
      - http
      - https
      default: https
    env:
      default: develop
      description: 'this value is related to the environment you are running. ie: PR-1112, develop'
    port:
      default: '8080'
    basePath:
      description: 'Version path. ie: v1'
      default: ''
tags:
- name: applications
paths:
  /v1/application/status:
    post:
      tags:
      - applications
      summary: Retrieve the current status of one or more applications
      description: Provide your requester identification UUID and a set of application/loan reference keys to get an up-to-date status on them.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicationStatusRequest'
      responses:
        200:
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/applicationStatusResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/UnexpectedError'
components:
  responses:
    BadRequest:
      description: Invalid request, unable to process the request with the information provided.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: b6c52a48-551a-42ef-b361-f642d25cfeb7
            status: BAD_REQUEST
            timestamp: '2019-10-21 14:07:59'
            message: Describes what was invalid about the request, if possible.
            debugMessage: null
    UnexpectedError:
      description: An unexpected server error occurred.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: b6c52a48-551a-42ef-b361-f642d25cfeb7
            status: INTERNAL_SERVER_ERROR
            timestamp: '2019-10-21 14:07:59'
            message: An internal issue occurred.  Please try again shortly.  If the issue persists, contact us with all of the data in this error message.
            debugMessage: null
  schemas:
    suberror:
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
        message:
          type: string
      example:
        object: Resource
        field: name
        rejectedValue: null
        message: must not be null
    applicationStatusResponse:
      type: object
      properties:
        applications:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/applicationStatus'
        errors:
          type: array
          items:
            allOf:
            - type: string
              example: String reference key of unretrievable application.
    error:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
        timestamp:
          type: string
        message:
          type: string
        debugMessage:
          type: string
        subErrors:
          type: array
          items:
            $ref: '#/components/schemas/suberror'
      example:
        id: null
        status: BAD_REQUEST
        timestamp: '2019-10-21 14:07:59'
        message: Validation error
        debugMessage: null
        subErrors:
        - object: Resource
          field: name
          rejectedValue: null
          message: must not be null
    applicationStatusRequest:
      type: object
      required:
      - referenceKeys
      - requester
      properties:
        referenceKeys:
          type: array
          items:
            allOf:
            - type: string
          example:
          - HIL-12345
          - HIL-98765
        requester:
          type: object
          allOf:
          - $ref: '#/components/schemas/requester'
    applicationStatus:
      type: object
      properties:
        loanStatus:
          type: string
          description: What stage the application/loan is on within the LendKey system.
        loanKey:
          type: string
          description: Unique identifier for application/loan
          example: HIL-12345
        loanAmount:
          type: number
          description: The loan amount for the application/loan - this is not the current balance for the account.
          example: 50000.0
        blockages:
          type: array
          items:
            allOf:
            - type: string
          description: A set of text describing what may be preventing the application/loan from advancing.
          example:
          - Waiting for contractor to submit a disbursement request.
    requester:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 40121260-4082-4c22-b70c-b5be137bf2a0
